### ISSUE TITLE
Uses context.api.setStylesheet in main function

### ISSUE THREAD

**Issue by TanninOne** [agc93/beatvortex#1]
This line: 
https://github.com/agc93/beatvortex/blob/3f45920213a4733374cc572bfab379dfa10eece0/src/index.ts#L89

has to be moved inside the context.once callback.

The reason being that the api object isn't fully initialized at the time the extension main function is invoked (extensions might be influencing the initialization) and thus shouldn't be used directly inside main (using it in callbacks is fine)

Vortex versions 1.2.3 and later will produce an error message for this to help avoid these kinds of mistakes but obviously for you that means your extension breaks for users with this update.

**Comment by agc93** [comment]
Thanks for the report @TanninOne , I had a chat with Picky in Discord last night about this.

Should be resolved in 0.2.2
