### ISSUE TITLE
error: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by TanninOne** [agc93/beatvortex#6]
Please see https://github.com/Nexus-Mods/Vortex/issues/6785
Pretty sure the mod being installed is important for this case: "Installing = Counters_-1.9.0"

**Comment by agc93** [comment]
So much for the predictability of the file names! I'll take a look at this, thanks for the heads up

**Comment by agc93** [comment]
@TanninOne The scourge of special characters strikes again 😆 I've fixed this (and buffed up the error handling) in 0.3.7 that I've just uploaded.

Thanks again for letting me know about this.
